### ISSUE TITLE
i am facing this error 

### ISSUE THREAD

**Issue by hinakhanvip1992** [SnoringDragon/gluetun-qbittorrent-port-manager#6]
Couldn't find file /tmp/gluetun/forwarded_port

![image](https://github.com/user-attachments/assets/8d884cf0-0071-4e85-a994-446357167871)

![image](https://github.com/user-attachments/assets/0db429ee-5bfc-4b97-a2ac-735c086bbded)

![image](https://github.com/user-attachments/assets/05ffe130-d211-4dad-aa23-f730cae7f5b4)

**Comment by ErnToTo** [comment]
Double check the volumes declarations in both containers and environment variables in qbit torrent port manager.
For example (parts of my docker compose file):
```yaml
# gluetun container
volumes:
  - $DOCKERDIR/appdata/gluetun/tmp:/tmp/gluetun

# qbit torrent port manager container
volumes:
  - $DOCKERDIR/appdata/gluetun/tmp:/tmp/gluetun
environment:
  PORT_FORWARDED: /tmp/gluetun/forwarded_port
```
