### ISSUE TITLE
Couldn't find file /tmp/gluetun/forwarded_port on synology

### ISSUE THREAD

**Issue by hohaha045** [SnoringDragon/gluetun-qbittorrent-port-manager#9]
Like the title said, port manager having issue find the forwarded port and I am not sure why

here's my full config
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}+pmp
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - PORT_FORWARD_ONLY=${PORT_FORWARD_ONLY}
      - VPN_PORT_FORWARDING=${VPN_PORT_FORWARDING}
    volumes:
      - /volume1/docker/qbittorrent-gluetun/gluetun:/gluetun
    ports:
      - ${WEBUI_PORT}:${WEBUI_PORT}
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - /volume1/docker/qbittorrent-gluetun/qbittorrent:/config
      - /volume1/downloads/torrents:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  gluetun-qbittorrent-port-manager:
    image: snoringdragon/gluetun-qbittorrent-port-manager:latest
    container_name: gluetun-qbittorrent-port-manager
    volumes:
    - /volume1/docker/qbittorrent-gluetun:/tmp/gluetun  # This points to the correct directory for Gluetun's configuration
    network_mode: service:gluetun
    environment:
      QBITTORRENT_SERVER: 192.168.1.9 # IP Address of qbittorrent
      QBITTORRENT_PORT: 8090
      QBITTORRENT_USER: # username
      QBITTORRENT_PASS: # password
      PORT_FORWARDED: /tmp/gluetun/forwarded_port
      HTTP_S: http # Select 'http' or 'https' depending on if you use certificates.
    restart: unless-stopped
```

I am using http://192.168.1.9:8090/ to access my qbittorrent web UI so the port, user name and password is correct, 
also tried SSH to my DSM and 
using
`ls -l /tmp/gluetun`
it return
```
-rw-r--r--    1 nonrootu 1000             5 Mar 11 17:16 forwarded_port
-rw-r--r--    1 nonrootu 1000            14 Mar 11 17:16 IP
```
so I guess my volumes is also correct?

in the gluetun log I can also see

<img width="905" alt="Image" src="https://github.com/user-attachments/assets/4dde03d6-f439-474e-becb-2cf33c45d4d7" />
So the VPN port forwarding seems fine

And I am not sure what went wrong
